name: Python 3.9, Keras 2.12
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *
  pull_request:
    branches:
      - main


jobs:
  run-tests:
    uses: ./.github/workflows/run_keras_tests.yml
    with:
      python-version: "3.9"
      tf-version: "2.12.*"